sudo: false

language: python

matrix:
    include:
        - dist: trusty
          python: "2.6"
        - dist: trusty
          python: "2.7"
        - dist: trusty
          python: "3.3"
        - dist: trusty
          python: "3.4"
        - dist: xenial
          python: "3.5"
        - dist: xenial
          python: "3.6"
        - dist: xenial
          python: "3.7"
        - dist: trusty
          python: "pypy"

env:
  - SLUGIFY_USES_TEXT_UNIDECODE=yes
  - SLUGIFY_USES_UNIDECODE=yes # dummy: tell travis to run more than one build types

install:
  - pip install pip -U
  - if [[ -z "${SLUGIFY_USES_TEXT_UNIDECODE}" ]]; then pip install -q -r requirements.txt; else pip install -q -r requirements_alt.txt; fi
  - pip install -e .
  - pip install pycodestyle
  - pip install coveralls
  - pip install https://github.com/un33k/pyflakes/tarball/master

before_script:
  - "bash pycodestyle.sh"
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W slugify; fi

script: coverage run --source=slugify test.py

after_success:
  coveralls
